### Imports

In [101]:
import numpy as np

### Auxiliar Functions

In [102]:
def swap_rows(M,row_index_1,row_index_2):
    M_ = M.copy()
    M_[[row_index_1,row_index_2]] = M[[row_index_2,row_index_1]]
    return M_

In [103]:
def get_index_first_non_zero_value_from_column(M,column,starting_row):
    column_array = M[starting_row:,column]
    print(column_array)
    for i, val in enumerate(column_array):
        if not np.isclose(val,0,atol=1e-5):
            index = i + starting_row
            return index
    
    return -1

In [104]:
def get_index_first_non_zero_value_from_row(M, row, augmented = False):
    M_ = M.copy()
    if augmented == True:
        M_ = M_[:,:-1]
    
    row_array = M_[row]
    for i, val in enumerate(row_array):
        if not np.isclose(val,0,atol=1e-5):
            return i
    return -1

In [105]:
def augmented_matrix(A,B):
    augmented_M = np.hstack((A,B))
    return augmented_M

In [161]:
def row_echelon_form(A, B):
    det_A = np.linalg.det(A)
    if np.isclose(det_A,0) == True:
        raise "Sigular System"
    
    A_ = A.copy()
    B_ = B.copy()

    A_ = A_.astype('float64')
    B_ = B_.astype('float64')

    num_rows = len(A) 
    M = augmented_matrix(A_,B_)
    print(M)
    for row in range(num_rows):
        pivot_candidate = M[row,row]
        print("current pivot:",pivot_candidate)
        if np.isclose(pivot_candidate,0) == True:

            first_non_zero_value_below_pivot_candidate = get_index_first_non_zero_value_from_column(M, row, row)
            print("first non zero below pivot candidate:",first_non_zero_value_below_pivot_candidate)
            M = swap_rows(M, row, first_non_zero_value_below_pivot_candidate)
            pivot = M[row,row]
        else:
            pivot = pivot_candidate
        
        M[row] = 1/pivot * M[row]

        for j in range(row + 1, num_rows):
            value_below_pivot = M[j,row]
            print("value_below_pivot:",M[j,row])
            print("Row value below * matriz[row]",value_below_pivot*M[row])
            M[j] = M[j] - value_below_pivot*M[row]
        
        print(M)
        print("________")
    print("finish")
    return (M)

In [ ]:
def back_substitution(M):
    M_ = M.copy()
    num_rows = M_.shape[0]
    for row in reversed(range(num_rows)): 
       print("current row pivot:",row)
       for j in range(row):
           print("  current row subs:",j)
           row_to_reduce = M_[j]
           print("      ",row_to_reduce)
           value = row_to_reduce[row]
           print("      value to reduce:",value)
           row_to_reduce = row_to_reduce - value*M_[row]
           M_[j,:] = row_to_reduce
    solution = M_[:,-1]
    print(M_)
    print(solution)

### Test

In [164]:
A = np.array([[-9, -1, -5],[-9, -9, -8],[ 0, -3, -8]])
B = np.array([[1],[4],[8]])
x = row_echelon_form(A,B)
back_substitution(x)

[[-9. -1. -5.  1.]
 [-9. -9. -8.  4.]
 [ 0. -3. -8.  8.]]
current pivot: -9.0
value_below_pivot: -9.0
Row value below * matriz[row] [-9. -1. -5.  1.]
value_below_pivot: 0.0
Row value below * matriz[row] [ 0.  0.  0. -0.]
[[ 1.          0.11111111  0.55555556 -0.11111111]
 [ 0.         -8.         -3.          3.        ]
 [ 0.         -3.         -8.          8.        ]]
________
current pivot: -8.0
value_below_pivot: -3.0
Row value below * matriz[row] [ 0.    -3.    -1.125  1.125]
[[ 1.          0.11111111  0.55555556 -0.11111111]
 [-0.          1.          0.375      -0.375     ]
 [ 0.          0.         -6.875       6.875     ]]
________
current pivot: -6.875
[[ 1.          0.11111111  0.55555556 -0.11111111]
 [-0.          1.          0.375      -0.375     ]
 [-0.         -0.          1.         -1.        ]]
________
finish
current row pivot: 2
  current row subs: 0
       [ 1.          0.11111111  0.55555556 -0.11111111]
      value to reduce: 0.5555555555555556
  current row s

### Test Auxiliar Functions

In [ ]:
A = np.array([[1,2,3],[0,1,0], [0,0,5]])
B = np.array([[1], [2], [4]])
row_echelon_form(A,B)

In [129]:
C = np.array([[1, 2, 3],[5, 0, 2], [1, 4, 5]])
B2 = np.array([[4],[3],[6]])

In [ ]:
x = row_echelon_form(C,B2)

In [140]:
x

array([[ 1.        ,  2.        ,  3.        ,  4.        ],
       [-0.        ,  1.        ,  1.3       ,  1.7       ],
       [-0.        , -0.        ,  1.        ,  2.33333333]])

In [155]:
back_substitution(x)

current row pivot: 2
  current row subs: 0
       [1. 2. 3. 4.]
      value to reduce: 3.0
  current row subs: 1
       [-0.   1.   1.3  1.7]
      value to reduce: 1.3
current row pivot: 1
  current row subs: 0
       [ 1.  2.  0. -3.]
      value to reduce: 2.0
current row pivot: 0
[[ 1.          0.          0.         -0.33333333]
 [ 0.          1.          0.         -1.33333333]
 [-0.         -0.          1.          2.33333333]]
[4.         1.7        2.33333333]


In [111]:
M = np.array([
[1, 3, 6],
[0, -5, 2],
[-4, 5, 8]
])
print(M)

[[ 1  3  6]
 [ 0 -5  2]
 [-4  5  8]]


In [ ]:
M_swapped = swap_rows(M, 0, 2)
print(M_swapped)

In [ ]:
N = np.array([
[0, 5, -3 ,6 ,8],
[0, 6, 3, 8, 1],
[0, 0, 0, 0, 0],
[0, 0, 0 ,0 ,7],
[0, 2, 1, 0, 4]
]
)
print(N)

In [11]:
print(get_index_first_non_zero_value_from_column(N, column = 0, starting_row = 0))

[0 0 0 0 0]
-1


In [12]:
print(get_index_first_non_zero_value_from_column(N, column = -1, starting_row = 2))

[0 7 4]
3


In [19]:
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3, augmented = True)}')

Output for row 3: -1


In [15]:
print(f'Output for row 2: {get_index_first_non_zero_value_from_row(N, 2)}')
print(f'Output for row 3: {get_index_first_non_zero_value_from_row(N, 3)}')

Output for row 2: -1
Output for row 3: 4


In [21]:
A = np.array([[1,2,3], [3,4,5], [4,5,6]])
B = np.array([[1], [5], [7]])

print(augmented_matrix(A,B))

[[1 2 3 1]
 [3 4 5 5]
 [4 5 6 7]]


[[1. 2. 3. 1.]
 [0. 1. 0. 2.]
 [0. 0. 5. 4.]]
current pivot: 1.0
________
current pivot: 0.0
[1. 0.]
first non zero below pivot candidate: 1
________
current pivot: 0.0
[5.]
first non zero below pivot candidate: 2
________
finish
[[1. 2. 3. 1.]
 [0. 1. 0. 2.]
 [0. 0. 5. 4.]]
